// <auto-generated />
using System;
using CooperateApplication.Repositories.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CooperateApplication.Repositories.Migrations
{
    [DbContext(typeof(CooperationDbContext))]
    [Migration("20230419031715_abc")]
    partial class abc
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.11");

            modelBuilder.Entity("CooperateApplication.Repositories.Entities.ClassStudent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime")
                        .HasColumnName("NgayTao");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("MajorsId")
                        .HasColumnType("int")
                        .HasColumnName("MaNganh");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("TenLop");

                    b.Property<bool>("Status")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("TrangThai");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("datetime")
                        .HasColumnName("NgayChinhSua");

                    b.HasKey("Id");

                    b.HasIndex("MajorsId");

                    b.ToTable("Lop");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateAt = new DateTime(2023, 4, 19, 3, 17, 15, 260, DateTimeKind.Utc).AddTicks(9610),
                            IsDeleted = false,
                            MajorsId = 1,
                            Name = "20T1",
                            Status = false
                        },
                        new
                        {
                            Id = 2,
                            CreateAt = new DateTime(2023, 4, 19, 3, 17, 15, 260, DateTimeKind.Utc).AddTicks(9934),
                            IsDeleted = false,
                            MajorsId = 1,
                            Name = "20T2",
                            Status = false
                        });
                });

            modelBuilder.Entity("CooperateApplication.Repositories.Entities.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime")
                        .HasColumnName("NgayTao");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("TenKhoa");

                    b.Property<bool>("Status")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("TrangThai");

                    b.Property<int>("UniversityId")
                        .HasColumnType("int")
                        .HasColumnName("MaTruong");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("datetime")
                        .HasColumnName("NgayChinhSua");

                    b.HasKey("Id");

                    b.HasIndex("UniversityId");

                    b.ToTable("Khoa");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateAt = new DateTime(2023, 4, 19, 3, 17, 15, 260, DateTimeKind.Utc).AddTicks(6064),
                            IsDeleted = false,
                            Name = "Khoa Công Nghệ Số",
                            Status = false,
                            UniversityId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreateAt = new DateTime(2023, 4, 19, 3, 17, 15, 260, DateTimeKind.Utc).AddTicks(6385),
                            IsDeleted = false,
                            Name = "Khoa Điện - Điện Tử",
                            Status = false,
                            UniversityId = 1
                        },
                        new
                        {
                            Id = 3,
                            CreateAt = new DateTime(2023, 4, 19, 3, 17, 15, 260, DateTimeKind.Utc).AddTicks(6432),
                            IsDeleted = false,
                            Name = "Khoa Cơ Khí",
                            Status = false,
                            UniversityId = 1
                        },
                        new
                        {
                            Id = 4,
                            CreateAt = new DateTime(2023, 4, 19, 3, 17, 15, 260, DateTimeKind.Utc).AddTicks(6529),
                            IsDeleted = false,
                            Name = "Khoa Xây Dựng",
                            Status = false,
                            UniversityId = 1
                        },
                        new
                        {
                            Id = 5,
                            CreateAt = new DateTime(2023, 4, 19, 3, 17, 15, 260, DateTimeKind.Utc).AddTicks(6561),
                            IsDeleted = false,
                            Name = "Khoa Hóa Học và Môi Trường",
                            Status = false,
                            UniversityId = 1
                        });
                });

            modelBuilder.Entity("CooperateApplication.Repositories.Entities.Enterprise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CorporateTaxCode")
                        .HasColumnType("text")
                        .HasColumnName("MaSoThue");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime")
                        .HasColumnName("NgayTao");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("GioiThieu");

                    b.Property<string>("Director")
                        .HasColumnType("text")
                        .HasColumnName("GiamDoc");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("ImageLogo")
                        .HasColumnType("text")
                        .HasColumnName("Logo");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("TenDoanhNghiep");

                    b.Property<string>("Phone")
                        .HasColumnType("text")
                        .HasColumnName("SoDienThoai");

                    b.Property<bool>("Status")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("TrangThai");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("datetime")
                        .HasColumnName("NgayChinhSua");

                    b.Property<string>("Website")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DoanhNghiep");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateAt = new DateTime(2023, 4, 19, 3, 17, 14, 876, DateTimeKind.Utc).AddTicks(2444),
                            Description = "Là doanh nghiệp phát triển các phần mềm ứng dụng chất lượng ca và ổn định",
                            Email = "hr@gmail.com",
                            IsDeleted = false,
                            Name = "Test Company",
                            Phone = "0325867435",
                            Status = false,
                            Website = "https://www.google.com.vn/"
                        });
                });

            modelBuilder.Entity("CooperateApplication.Repositories.Entities.EnterpriseEmployee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime")
                        .HasColumnName("NgayTao");

                    b.Property<int>("EnterpriseId")
                        .HasColumnType("int")
                        .HasColumnName("MaDoanhNghiep");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("Status")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("TrangThai");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("datetime")
                        .HasColumnName("NgayChinhSua");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("MaNguoiDung");

                    b.HasKey("Id");

                    b.HasIndex("EnterpriseId");

                    b.HasIndex("UserId");

                    b.ToTable("NhanVien");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateAt = new DateTime(2023, 4, 19, 3, 17, 15, 72, DateTimeKind.Utc).AddTicks(2875),
                            EnterpriseId = 1,
                            IsDeleted = false,
                            Status = false,
                            UserId = 2
                        },
                        new
                        {
                            Id = 2,
                            CreateAt = new DateTime(2023, 4, 19, 3, 17, 15, 259, DateTimeKind.Utc).AddTicks(7923),
                            EnterpriseId = 1,
                            IsDeleted = false,
                            Status = false,
                            UserId = 3
                        });
                });

            modelBuilder.Entity("CooperateApplication.Repositories.Entities.EnterpriseFacility", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime")
                        .HasColumnName("NgayTao");

                    b.Property<string>("DetailAddress")
                        .HasColumnType("text")
                        .HasColumnName("DiaChiCuThe");

                    b.Property<int>("EnterpriseId")
                        .HasColumnType("int")
                        .HasColumnName("MaDoanhNghiep");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("TenChiNhanh");

                    b.Property<string>("ProvinceAddress")
                        .HasColumnType("text")
                        .HasColumnName("Tinh");

                    b.Property<bool>("Status")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("TrangThai");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("datetime")
                        .HasColumnName("NgayChinhSua");

                    b.HasKey("Id");

                    b.HasIndex("EnterpriseId");

                    b.ToTable("ChiNhanhDoanhNghiep");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateAt = new DateTime(2023, 4, 19, 3, 17, 15, 260, DateTimeKind.Utc).AddTicks(1578),
                            DetailAddress = "Đường 3/2",
                            EnterpriseId = 1,
                            IsDeleted = false,
                            Name = "Tầng 23, Tòa nhà ACB Bank",
                            ProvinceAddress = "Thuận Phước",
                            Status = false
                        },
                        new
                        {
                            Id = 2,
                            CreateAt = new DateTime(2023, 4, 19, 3, 17, 15, 260, DateTimeKind.Utc).AddTicks(1934),
                            DetailAddress = "Đường Hùng Vương",
                            EnterpriseId = 1,
                            IsDeleted = false,
                            Name = "Tầng 13, Tòa nhà Viettin Bank",
                            ProvinceAddress = "Hải Châu",
                            Status = false
                        });
                });

            modelBuilder.Entity("CooperateApplication.Repositories.Entities.EnterpriseField", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime")
                        .HasColumnName("NgayTao");

                    b.Property<int>("EnterpriseId")
                        .HasColumnType("int")
                        .HasColumnName("MaDoanhNghiep");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("TenLinhVuc");

                    b.Property<bool>("Status")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("TrangThai");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("datetime")
                        .HasColumnName("NgayChinhSua");

                    b.HasKey("Id");

                    b.HasIndex("EnterpriseId");

                    b.ToTable("LinhVucKinhDoanh");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateAt = new DateTime(2023, 4, 19, 3, 17, 15, 260, DateTimeKind.Utc).AddTicks(3150),
                            EnterpriseId = 1,
                            IsDeleted = false,
                            Name = "Software",
                            Status = false
                        },
                        new
                        {
                            Id = 2,
                            CreateAt = new DateTime(2023, 4, 19, 3, 17, 15, 260, DateTimeKind.Utc).AddTicks(3434),
                            EnterpriseId = 1,
                            IsDeleted = false,
                            Name = "Giải trí/ Game",
                            Status = false
                        },
                        new
                        {
                            Id = 3,
                            CreateAt = new DateTime(2023, 4, 19, 3, 17, 15, 260, DateTimeKind.Utc).AddTicks(3513),
                            EnterpriseId = 1,
                            IsDeleted = false,
                            Name = "Dịch vụ IT",
                            Status = false
                        });
                });

            modelBuilder.Entity("CooperateApplication.Repositories.Entities.Majors", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime")
                        .HasColumnName("NgayTao");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int")
                        .HasColumnName("MaKhoa");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("TenNganh");

                    b.Property<bool>("Status")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("TrangThai");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("datetime")
                        .HasColumnName("NgayChinhSua");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Nganh");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateAt = new DateTime(2023, 4, 19, 3, 17, 15, 260, DateTimeKind.Utc).AddTicks(7654),
                            DepartmentId = 1,
                            IsDeleted = false,
                            Name = "Ngành Công Nghệ Thông Tin",
                            Status = false
                        },
                        new
                        {
                            Id = 2,
                            CreateAt = new DateTime(2023, 4, 19, 3, 17, 15, 260, DateTimeKind.Utc).AddTicks(7784),
                            DepartmentId = 2,
                            IsDeleted = false,
                            Name = "Ngành Công nghệ kỹ thuật nhiệt",
                            Status = false
                        },
                        new
                        {
                            Id = 3,
                            CreateAt = new DateTime(2023, 4, 19, 3, 17, 15, 260, DateTimeKind.Utc).AddTicks(7816),
                            DepartmentId = 2,
                            IsDeleted = false,
                            Name = "Ngành Công nghệ kỹ thuật điện, điện tử",
                            Status = false
                        },
                        new
                        {
                            Id = 5,
                            CreateAt = new DateTime(2023, 4, 19, 3, 17, 15, 260, DateTimeKind.Utc).AddTicks(7845),
                            DepartmentId = 2,
                            IsDeleted = false,
                            Name = "Ngành Công nghệ kỹ thuật điện tử - viễn thông",
                            Status = false
                        },
                        new
                        {
                            Id = 6,
                            CreateAt = new DateTime(2023, 4, 19, 3, 17, 15, 260, DateTimeKind.Utc).AddTicks(7874),
                            DepartmentId = 2,
                            IsDeleted = false,
                            Name = "Ngành Công nghệ kỹ thuật điều khiển và tự động hóa",
                            Status = false
                        },
                        new
                        {
                            Id = 7,
                            CreateAt = new DateTime(2023, 4, 19, 3, 17, 15, 260, DateTimeKind.Utc).AddTicks(7904),
                            DepartmentId = 3,
                            IsDeleted = false,
                            Name = "Ngành Công nghệ kỹ thuật cơ khí",
                            Status = false
                        },
                        new
                        {
                            Id = 8,
                            CreateAt = new DateTime(2023, 4, 19, 3, 17, 15, 260, DateTimeKind.Utc).AddTicks(7933),
                            DepartmentId = 3,
                            IsDeleted = false,
                            Name = "Ngành Công nghệ kỹ thuật cơ điện tử",
                            Status = false
                        },
                        new
                        {
                            Id = 9,
                            CreateAt = new DateTime(2023, 4, 19, 3, 17, 15, 260, DateTimeKind.Utc).AddTicks(7962),
                            DepartmentId = 4,
                            IsDeleted = false,
                            Name = "Ngành Công nghệ kỹ thuật xây dựng",
                            Status = false
                        },
                        new
                        {
                            Id = 10,
                            CreateAt = new DateTime(2023, 4, 19, 3, 17, 15, 260, DateTimeKind.Utc).AddTicks(7992),
                            DepartmentId = 4,
                            IsDeleted = false,
                            Name = "Ngành Công nghệ kỹ thuật giao thông",
                            Status = false
                        },
                        new
                        {
                            Id = 11,
                            CreateAt = new DateTime(2023, 4, 19, 3, 17, 15, 260, DateTimeKind.Utc).AddTicks(8023),
                            DepartmentId = 4,
                            IsDeleted = false,
                            Name = "Ngành Công nghệ kỹ thuật kiến trúc",
                            Status = false
                        },
                        new
                        {
                            Id = 12,
                            CreateAt = new DateTime(2023, 4, 19, 3, 17, 15, 260, DateTimeKind.Utc).AddTicks(8052),
                            DepartmentId = 4,
                            IsDeleted = false,
                            Name = "Kỹ thuật cơ sở hạ tầng",
                            Status = false
                        },
                        new
                        {
                            Id = 13,
                            CreateAt = new DateTime(2023, 4, 19, 3, 17, 15, 260, DateTimeKind.Utc).AddTicks(8124),
                            DepartmentId = 5,
                            IsDeleted = false,
                            Name = "Công nghệ kỹ thuật môi trường",
                            Status = false
                        },
                        new
                        {
                            Id = 14,
                            CreateAt = new DateTime(2023, 4, 19, 3, 17, 15, 260, DateTimeKind.Utc).AddTicks(8161),
                            DepartmentId = 5,
                            IsDeleted = false,
                            Name = "Ngành Kỹ Thuật thực phẩm",
                            Status = false
                        },
                        new
                        {
                            Id = 15,
                            CreateAt = new DateTime(2023, 4, 19, 3, 17, 15, 260, DateTimeKind.Utc).AddTicks(8583),
                            DepartmentId = 5,
                            IsDeleted = false,
                            Name = "Ngành Công nghệ vật liệu",
                            Status = false
                        });
                });

            modelBuilder.Entity("CooperateApplication.Repositories.Entities.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime")
                        .HasColumnName("NgayTao");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("NoiDung");

                    b.Property<string>("Image")
                        .HasColumnType("text")
                        .HasColumnName("HinhAnh");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("Status")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("TrangThai");

                    b.Property<string>("Title")
                        .HasColumnType("text")
                        .HasColumnName("TieuDe");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("datetime")
                        .HasColumnName("NgayChinhSua");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("MaNguoiDung");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("ThongBao");
                });

            modelBuilder.Entity("CooperateApplication.Repositories.Entities.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime")
                        .HasColumnName("NgayTao");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("MoTa");

                    b.Property<int>("EnterpriseId")
                        .HasColumnType("int")
                        .HasColumnName("MaDoanhNghiep");

                    b.Property<DateTime>("ExpireTime")
                        .HasColumnType("datetime")
                        .HasColumnName("HanCuoi");

                    b.Property<string>("Image")
                        .HasColumnType("text")
                        .HasColumnName("HinhAnh");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("SoLuong");

                    b.Property<bool>("Status")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("TrangThai");

                    b.Property<string>("Title")
                        .HasColumnType("text")
                        .HasColumnName("TieuDe");

                    b.Property<int>("Type")
                        .HasColumnType("int")
                        .HasColumnName("LoaiBai");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("datetime")
                        .HasColumnName("NgayChinhSua");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("MaNguoiDung");

                    b.HasKey("Id");

                    b.HasIndex("EnterpriseId");

                    b.HasIndex("UserId");

                    b.ToTable("BaiDang");
                });

            modelBuilder.Entity("CooperateApplication.Repositories.Entities.PostMajors", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime")
                        .HasColumnName("NgayTao");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("MajorsId")
                        .HasColumnType("int")
                        .HasColumnName("MaNganh");

                    b.Property<int>("PostId")
                        .HasColumnType("int")
                        .HasColumnName("MaBaiDang");

                    b.Property<bool>("Status")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("TrangThai");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("datetime")
                        .HasColumnName("NgayChinhSua");

                    b.HasKey("Id");

                    b.HasIndex("MajorsId");

                    b.HasIndex("PostId");

                    b.ToTable("NganhBaiDang");
                });

            modelBuilder.Entity("CooperateApplication.Repositories.Entities.PostStudent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime")
                        .HasColumnName("NgayTao");

                    b.Property<bool>("IsAccept")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("DuyetDangKi");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("PostId")
                        .HasColumnType("int")
                        .HasColumnName("MaBaiDang");

                    b.Property<bool>("Status")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("TrangThai");

                    b.Property<int>("StudentId")
                        .HasColumnType("int")
                        .HasColumnName("MaSinhVien");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("datetime")
                        .HasColumnName("NgayChinhSua");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.HasIndex("StudentId");

                    b.ToTable("SinhVienTuyenDung");
                });

            modelBuilder.Entity("CooperateApplication.Repositories.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime")
                        .HasColumnName("NgayTao");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("RoleName")
                        .HasColumnType("text")
                        .HasColumnName("TenQuyen");

                    b.Property<bool>("Status")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("TrangThai");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("datetime")
                        .HasColumnName("NgayChinhSua");

                    b.HasKey("Id");

                    b.ToTable("Quyen");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateAt = new DateTime(2023, 4, 19, 3, 17, 14, 659, DateTimeKind.Utc).AddTicks(410),
                            IsDeleted = false,
                            RoleName = "Administrator",
                            Status = false
                        },
                        new
                        {
                            Id = 2,
                            CreateAt = new DateTime(2023, 4, 19, 3, 17, 14, 660, DateTimeKind.Utc).AddTicks(227),
                            IsDeleted = false,
                            RoleName = "EmployeeHRM",
                            Status = false
                        },
                        new
                        {
                            Id = 3,
                            CreateAt = new DateTime(2023, 4, 19, 3, 17, 14, 660, DateTimeKind.Utc).AddTicks(330),
                            IsDeleted = false,
                            RoleName = "EmployeeMentor",
                            Status = false
                        },
                        new
                        {
                            Id = 4,
                            CreateAt = new DateTime(2023, 4, 19, 3, 17, 14, 660, DateTimeKind.Utc).AddTicks(362),
                            IsDeleted = false,
                            RoleName = "EmployeeAdmin",
                            Status = false
                        },
                        new
                        {
                            Id = 5,
                            CreateAt = new DateTime(2023, 4, 19, 3, 17, 14, 660, DateTimeKind.Utc).AddTicks(383),
                            IsDeleted = false,
                            RoleName = "Student",
                            Status = false
                        });
                });

            modelBuilder.Entity("CooperateApplication.Repositories.Entities.SenimarStudent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime")
                        .HasColumnName("NgayTao");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("PostId")
                        .HasColumnType("int")
                        .HasColumnName("MaBaiDang");

                    b.Property<bool>("Status")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("TrangThai");

                    b.Property<int>("StudentId")
                        .HasColumnType("int")
                        .HasColumnName("MaSinhVien");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("datetime")
                        .HasColumnName("NgayChinhSua");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.HasIndex("StudentId");

                    b.ToTable("SinhVienHoiThao");
                });

            modelBuilder.Entity("CooperateApplication.Repositories.Entities.SlideImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime")
                        .HasColumnName("NgayTao");

                    b.Property<string>("Image")
                        .HasColumnType("text")
                        .HasColumnName("HinhAnh");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsEnable")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("KichHoat");

                    b.Property<bool>("Status")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("TrangThai");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("datetime")
                        .HasColumnName("NgayChinhSua");

                    b.HasKey("Id");

                    b.ToTable("Banner");
                });

            modelBuilder.Entity("CooperateApplication.Repositories.Entities.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ClassId")
                        .HasColumnType("int")
                        .HasColumnName("MaLop");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime")
                        .HasColumnName("NgayTao");

                    b.Property<string>("FileCV")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("Status")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("TrangThai");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("datetime")
                        .HasColumnName("NgayChinhSua");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("MaNguoiDung");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.HasIndex("UserId");

                    b.ToTable("SinhVien");
                });

            modelBuilder.Entity("CooperateApplication.Repositories.Entities.University", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasColumnType("text")
                        .HasColumnName("DiaChi");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime")
                        .HasColumnName("NgayTao");

                    b.Property<string>("Introduction")
                        .HasColumnType("text")
                        .HasColumnName("GioiThieu");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("TenTruong");

                    b.Property<bool>("Status")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("TrangThai");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("datetime")
                        .HasColumnName("NgayChinhSua");

                    b.HasKey("Id");

                    b.ToTable("Truong");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Đà Nẵng",
                            CreateAt = new DateTime(2023, 4, 19, 3, 17, 15, 260, DateTimeKind.Utc).AddTicks(4914),
                            Introduction = "description",
                            IsDeleted = false,
                            Name = "Test University",
                            Status = false
                        });
                });

            modelBuilder.Entity("CooperateApplication.Repositories.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Avatar")
                        .HasColumnType("text");

                    b.Property<DateTime>("Birthday")
                        .HasColumnType("datetime")
                        .HasColumnName("NgaySinh");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime")
                        .HasColumnName("NgayTao");

                    b.Property<string>("DetailAddress")
                        .HasColumnType("text")
                        .HasColumnName("DiaChiCuThe");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .HasColumnType("text")
                        .HasColumnName("Ten");

                    b.Property<bool>("Gender")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("GioiTinh");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Password")
                        .HasColumnType("text")
                        .HasColumnName("MatKhau");

                    b.Property<string>("Phone")
                        .HasColumnType("text")
                        .HasColumnName("SoDienThoai");

                    b.Property<string>("ProvinceAddress")
                        .HasColumnType("text")
                        .HasColumnName("DiaChi");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text");

                    b.Property<DateTime>("RefreshTokenExpiryTime")
                        .HasColumnType("datetime");

                    b.Property<bool>("Status")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("TrangThai");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("datetime")
                        .HasColumnName("NgayChinhSua");

                    b.Property<string>("UserName")
                        .HasColumnType("text")
                        .HasColumnName("TaiKhoan");

                    b.Property<int>("UserType")
                        .HasColumnType("int")
                        .HasColumnName("LoaiNguoiDung");

                    b.HasKey("Id");

                    b.ToTable("NguoiDung");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Birthday = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreateAt = new DateTime(2023, 4, 19, 3, 17, 14, 875, DateTimeKind.Utc).AddTicks(9718),
                            FullName = "Quản trị viên 1",
                            Gender = false,
                            IsDeleted = false,
                            Password = "$2a$11$1S0JhB3xoqMQjJeHpacEguh2U1IIdJpiUpLLAZDQqUPuxOePdkU92",
                            RefreshTokenExpiryTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = false,
                            UserName = "admin",
                            UserType = 0
                        },
                        new
                        {
                            Id = 2,
                            Birthday = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreateAt = new DateTime(2023, 4, 19, 3, 17, 15, 72, DateTimeKind.Utc).AddTicks(933),
                            FullName = "Employee HRM",
                            Gender = false,
                            IsDeleted = false,
                            Password = "$2a$11$QgXsvjLeWgxG0DiHPKvzxeSdvJjb8LH23GCAIzN.yu5NHO4jswG.6",
                            RefreshTokenExpiryTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = false,
                            UserName = "employee_hrm",
                            UserType = 1
                        },
                        new
                        {
                            Id = 3,
                            Birthday = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreateAt = new DateTime(2023, 4, 19, 3, 17, 15, 259, DateTimeKind.Utc).AddTicks(6903),
                            FullName = "Employee admin",
                            Gender = false,
                            IsDeleted = false,
                            Password = "$2a$11$Kp2XIGXMBG9Dxr1GC3kr.eZVyQWZuEjapn6RkianIPkVKOBKaBodK",
                            RefreshTokenExpiryTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = false,
                            UserName = "employee_admin",
                            UserType = 1
                        });
                });

            modelBuilder.Entity("CooperateApplication.Repositories.Entities.UserRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime")
                        .HasColumnName("NgayTao");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("MaQuyen");

                    b.Property<bool>("Status")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("TrangThai");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("datetime")
                        .HasColumnName("NgayChinhSua");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("MaNguoiDung");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("QuyenNguoiDung");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateAt = new DateTime(2023, 4, 19, 3, 17, 14, 876, DateTimeKind.Utc).AddTicks(1202),
                            IsDeleted = false,
                            RoleId = 1,
                            Status = false,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreateAt = new DateTime(2023, 4, 19, 3, 17, 15, 72, DateTimeKind.Utc).AddTicks(3136),
                            IsDeleted = false,
                            RoleId = 2,
                            Status = false,
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            CreateAt = new DateTime(2023, 4, 19, 3, 17, 15, 259, DateTimeKind.Utc).AddTicks(7744),
                            IsDeleted = false,
                            RoleId = 4,
                            Status = false,
                            UserId = 3
                        });
                });

            modelBuilder.Entity("CooperateApplication.Repositories.Entities.ClassStudent", b =>
                {
                    b.HasOne("CooperateApplication.Repositories.Entities.Majors", "Majors")
                        .WithMany()
                        .HasForeignKey("MajorsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Majors");
                });

            modelBuilder.Entity("CooperateApplication.Repositories.Entities.Department", b =>
                {
                    b.HasOne("CooperateApplication.Repositories.Entities.University", "University")
                        .WithMany()
                        .HasForeignKey("UniversityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("University");
                });

            modelBuilder.Entity("CooperateApplication.Repositories.Entities.EnterpriseEmployee", b =>
                {
                    b.HasOne("CooperateApplication.Repositories.Entities.Enterprise", "Enterprise")
                        .WithMany()
                        .HasForeignKey("EnterpriseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CooperateApplication.Repositories.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Enterprise");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CooperateApplication.Repositories.Entities.EnterpriseFacility", b =>
                {
                    b.HasOne("CooperateApplication.Repositories.Entities.Enterprise", "Enterprise")
                        .WithMany()
                        .HasForeignKey("EnterpriseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Enterprise");
                });

            modelBuilder.Entity("CooperateApplication.Repositories.Entities.EnterpriseField", b =>
                {
                    b.HasOne("CooperateApplication.Repositories.Entities.Enterprise", "Enterprise")
                        .WithMany()
                        .HasForeignKey("EnterpriseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Enterprise");
                });

            modelBuilder.Entity("CooperateApplication.Repositories.Entities.Majors", b =>
                {
                    b.HasOne("CooperateApplication.Repositories.Entities.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("CooperateApplication.Repositories.Entities.Notification", b =>
                {
                    b.HasOne("CooperateApplication.Repositories.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CooperateApplication.Repositories.Entities.Post", b =>
                {
                    b.HasOne("CooperateApplication.Repositories.Entities.Enterprise", "Enterprise")
                        .WithMany()
                        .HasForeignKey("EnterpriseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CooperateApplication.Repositories.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Enterprise");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CooperateApplication.Repositories.Entities.PostMajors", b =>
                {
                    b.HasOne("CooperateApplication.Repositories.Entities.Majors", "Majors")
                        .WithMany()
                        .HasForeignKey("MajorsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CooperateApplication.Repositories.Entities.Post", "Post")
                        .WithMany()
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Majors");

                    b.Navigation("Post");
                });

            modelBuilder.Entity("CooperateApplication.Repositories.Entities.PostStudent", b =>
                {
                    b.HasOne("CooperateApplication.Repositories.Entities.Post", "Post")
                        .WithMany()
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CooperateApplication.Repositories.Entities.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("CooperateApplication.Repositories.Entities.SenimarStudent", b =>
                {
                    b.HasOne("CooperateApplication.Repositories.Entities.Post", "Post")
                        .WithMany()
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CooperateApplication.Repositories.Entities.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("CooperateApplication.Repositories.Entities.Student", b =>
                {
                    b.HasOne("CooperateApplication.Repositories.Entities.ClassStudent", "Class")
                        .WithMany()
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CooperateApplication.Repositories.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CooperateApplication.Repositories.Entities.UserRole", b =>
                {
                    b.HasOne("CooperateApplication.Repositories.Entities.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CooperateApplication.Repositories.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
